/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package happypaws;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lenovo
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    
        
    DefaultTableModel dm;
    Connection con = null;
    PreparedStatement pre = null;
    PreparedStatement pre2 = null;
    PreparedStatement pre4 = null;
    PreparedStatement pre5 = null;
    ResultSet res = null;
    ResultSet res2 = null;
    ResultSet res3 = null;
    ResultSet res4 = null;
    ResultSet res5 = null;
    int flag=0;
    
    public Checkout() {
        initComponents();
        con = Connect.connect();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 369, 350, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1407, 417, 297, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 558, 445, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 605, 393, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 369, 390, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 417, 346, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 320, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 503, 376, 30));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 674, 350, 30));

        jComboBox1.setBackground(new java.awt.Color(255, 113, 113));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Online Payment" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 300, 30));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 465, 415, 30));

        jTextField12.setToolTipText("");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1388, 512, 317, 30));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 886, 70, 70));

        jButton1.setBackground(new java.awt.Color(156, 70, 81));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 760, 120, 30));

        jButton2.setBackground(new java.awt.Color(156, 70, 81));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 760, 120, 30));

        jButton4.setBackground(new java.awt.Color(156, 70, 81));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Checkout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 760, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/happypaws/checkout.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1920, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DateTimeFormatter date_formate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                
                String inDate = jTextField6.getText();
                String outDate = jTextField7.getText();
                
                LocalDate date1 = LocalDate.parse(inDate, date_formate);
                LocalDate date2 = LocalDate.parse(outDate, date_formate);
                long daysBetween = ChronoUnit.DAYS.between(date1, date2);
                String days = String.valueOf(daysBetween);
                jTextField8.setText(days);
                
                String room = jTextField5.getText();
                long total=0;
                
                int d = Integer.parseInt(jTextField8.getText());
                
                if(room.equals("Tom")){
                    total=d*650;
                    flag=1;
                }
                else if(room.equals("Pluto")){
                    total=d*1200;
                    flag=0;
                }
                
                String price = String.valueOf(total);
                jTextField10.setText(price);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        try {
            int petID = Integer.parseInt(jTextField3.getText());
            
            Statement st = con.createStatement();
            res = st.executeQuery("SELECT pets.Pet_Name, customer.Customer_ID, customer.Customer_Name, rooms.Type,  reservationInfo.Check_In_Date, reservationInfo.Check_Out_Date,  customer.Address, customer.Phone_Number \n"
                    +"FROM pets \n"
                    +"join customer \n"
                    +"on customer.Customer_ID = pets.CustomerID \n"
                    +"join rooms \n"
                    +"on rooms.Pet_ID = pets.Pet_Id \n"
                    +"join reservationInfo \n"
                    +"on reservationInfo.Pet_ID = pets.Pet_Id \n"
                    +"where pets.Pet_Id=" +petID);
            
            if(res.next()){
                
                jTextField4.setText(res.getString(1));
                jTextField1.setText(res.getString(2));
                jTextField2.setText(res.getString(3));
                jTextField5.setText(res.getString(4));
                jTextField6.setText(res.getString(5));
                jTextField7.setText(res.getString(6));
                jTextField11.setText(res.getString(7));
                jTextField12.setText(res.getString(8));
                
                DateTimeFormatter date_formate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                
                String inDate = jTextField6.getText();
                String outDate = jTextField7.getText();
                
                LocalDate date1 = LocalDate.parse(inDate, date_formate);
                LocalDate date2 = LocalDate.parse(outDate, date_formate);
                long daysBetween = ChronoUnit.DAYS.between(date1, date2);
                String days = String.valueOf(daysBetween);
                jTextField8.setText(days);
                
                String room = jTextField5.getText();
                long total=0;
                
                int d = Integer.parseInt(jTextField8.getText());
                
                if(room.equals("Tom")){
                    total=d*650;
                    flag=1;
                }
                else if(room.equals("Pluto")){
                    total=d*1200;
                    flag=0;
                }
                
                String price = String.valueOf(total);
                jTextField10.setText(price);
                
            }
            else{
                jTextField3.setText("");
                JOptionPane.showMessageDialog(null, "Invalid Pet ID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
            int amount = Integer.parseInt(jTextField10.getText());
            String date = jTextField7.getText();
            String method = (String)jComboBox1.getSelectedItem();
            int days = Integer.parseInt(jTextField8.getText());
            int cID = Integer.parseInt(jTextField1.getText());
            int pID = Integer.parseInt(jTextField3.getText());
            
            pre = con.prepareStatement("insert into bill(Bill_Amount,Bill_Date,Payment_Method) values(?,?,?)");
            
            pre.setInt(1, amount);
            pre.setString(2, date);
            pre.setString(3, method);
            
            pre.executeUpdate();
            
            int row1 = -1;
            int row2 = -1;
            int row3 = -1;
            int row4 = -1;
            int row5 = -1;
            int row6 = -1;
            
            String sql1 = "UPDATE rooms set Pet_ID = NULL, Availability = 'YES' WHERE Pet_ID = " +pID;
            Statement st1 = con.createStatement();
            row1 = st1.executeUpdate(sql1);
      
            String sql6 = "UPDATE food set Amount = (Amount-" +days+ ") WHERE Name = (select Food from pets where Pet_Id = " +pID+ ")";
            Statement st6 = con.createStatement();
            row6 = st6.executeUpdate(sql6); 

            String sql2 = "DELETE from medicine where Pet_ID  = " +pID;
            Statement st2 = con.createStatement();
            row2 = st2.executeUpdate(sql2);

            String sql3 = "DELETE from reservationInfo where Pet_ID = " +pID;
            Statement st3 = con.createStatement();
            row3 = st3.executeUpdate(sql3);
            
            String sql4 = "DELETE from pets where Pet_Id = " +pID;
            Statement st4 = con.createStatement();
            row4 = st4.executeUpdate(sql4);

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            
            JOptionPane.showMessageDialog(null, "Checkout Complete");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            int cID = Integer.parseInt(jTextField1.getText());
            int pID = Integer.parseInt(jTextField3.getText());
            String cName = jTextField2.getText();
            String address = jTextField11.getText();
            String num = jTextField12.getText();
            String pName = jTextField4.getText();
            String room = jTextField5.getText();
            String in = jTextField6.getText();
            String out = jTextField7.getText();
            String days = jTextField8.getText();
            String amount = jTextField10.getText();
            String method = (String)jComboBox1.getSelectedItem();
            
            pre4 = con.prepareStatement("select top 1 Bill_ID from bill order by Bill_ID desc");
            res4 = pre4.executeQuery();
            int bID = 0;
            while(res4.next())
            {
                bID = res4.getInt("Bill_ID")+1;
            }
            
            pre5 = con.prepareStatement("select Room_ID from rooms where Pet_ID = " +pID);
            res5 = pre5.executeQuery();
            int rID = 0;
            while(res5.next())
            {
                rID = res5.getInt("Room_ID");
            }
            
            String path="E:\\3.1\\db";
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+cID+".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                                                    HappyPaws\n\n");
            doc.add(paragraph1);
            
            Paragraph paragraph2 = new Paragraph("\n                                                                                                                     Date : "+ out+"\n\n              Bill No. : "+ bID+ "\n\n              Customer Name : "+ cName+ "\n              Address : "+ address+ "\n              Contact No. : "+ num+ "\n              Pet Name : "+ pName+ "\n              Check-In Date : "+ in+ "\n              Check-Out Date : "+ out+ "\n              Payment Method : "+ method+ "\n\n\n\n");
            doc.add(paragraph2);
            
            PdfPTable tb1 = new PdfPTable(5);
            tb1.addCell("Room No.");
            tb1.addCell("Room Type");
            tb1.addCell("Price/Night");
            tb1.addCell("No. of Nights");
            tb1.addCell("Total");
            tb1.addCell(Integer.toString(rID));
            tb1.addCell(room);
            if(flag==1){
                tb1.addCell("650");
            }
            else if(flag==0){
                tb1.addCell("1200");
            }
            
            tb1.addCell(days);
            tb1.addCell(amount);
            doc.add(tb1);
            
            Paragraph paragraph3 = new Paragraph("\n\n\n                           Bidding furwell with wagging tails and joyful barks at Happy Paws!\n" +
                                                 "                                               Your pets' paradise awaits, come again!");
            doc.add(paragraph3);
            
            JOptionPane.showMessageDialog(null, "Bill Generated!");
            doc.close();

        } catch (DocumentException | FileNotFoundException | SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
